### ISSUE TITLE
Clarification of /library page

### ISSUE THREAD

**Issue by Alexever17** [Chingu-cohorts/devgaido#71]
**_Issue Description & Expected Outcome:_** 
I think the structure of the page http://www.devgaido.com/library 
is not clear enough, because you just have many boxes with very different content

I fill like it would be a good to actually have some headlines before the different sections and also 
the road maps have the same color as the lessons   and that is not good 

**_Resolution:_** 
Some like this: http://cdn.proxer.me/f/2Iafz5ln
I am sorry for the bad quality, i just wanted to make a quick picture to explain what i mean.

**Comment by jdmedlock** [comment]
The next MVP#1 Release of devGaido contains enhancements to the formatting of paths and the learning content they contain. This includes consistent formatting as will as reformatting to improve clarity. Let's revisit this issue after you've had a chance to review the new release.

**Comment by jdmedlock** [comment]
@Alexever17 We've just installed a new release of the app which contains unique icons and heading colors on the lesson cards to signify whether they are paths or lessons. In an upcoming release we will also be adding an additional filter to limit the display to only paths or lessons. The Library page won't show the current paths or lessons as a separate section since we use the dashboard page for this type of view. Please take a look at the updated library page and let us know if it addresses your concern.

**Comment by jdmedlock** [comment]
Added a filtering option to display only paths or lessons to help distinguish between the two. This will be moved to Production later this week.

**Comment by kimkwanka** [comment]
Added tabs to live version.
