### ISSUE TITLE
When Logged In Library Page Does Not Reflect Number of Completed Lessons

### ISSUE THREAD

**Issue by AgedLace** [Chingu-cohorts/devgaido#75]
**_Issue Description & Expected Outcome:_** 
While still logged in and on the "Dashboard" Page, in the banner on the right hand side is a neat visual of my current status ... i.e. Completed:  0 Paths, 2 Classes 5 Lessons.
I tried to insert a screen grab here but it didn't work :(

When I switch to the Library Page, my JavaScript selection has been preserved, but when I look at the P1XT Guide box, the course progress icon in the lower right corner of that box still says 0/5 classes completed. 
Again, I tried to insert another screen grab.  Not sure what I'm doing wrong here :(

**_Symptoms:_**
On Library Page the P1XT Guide box course progress icon in the lower right corner does not reflect number of classes completed. 

**_Steps to Recreate:_** 
- Login to Dashboard
- Observe Progress in the lower right corner of the Banner  "Completed 0 Paths, 2 Classes 5 Lessons
- Use link above Banner to switch to the Library Page
- Observe P1XT Guide Box - specifically lower right hand corner; it still indicates 0/5 classes completed.

**_Resolution:_** 
Sync the progress from Dashboard to Library Page for individual classes within a Path.

**Comment by kimkwanka** [comment]
Which lessons did you complete exactly (and which courses)? I'm asking because both the metrics and the cards on the library page use the same data. Are you sure you have actually completed a full course on the P1XT Guide Path? Check the "Completed" Tab on your Dashboard to see which courses the app considers to be completed. Because of the fact that lessons are oftentimes shared between multiple courses it could just be the case that those 5 lessons you completed, marked 2 courses which are NOT part of the P1XT guide as "completed" since they use the same lessons. The P1XT Path Card would only show 1/5 if you actually completed all the lessons in that course.

**Comment by AgedLace** [comment]
Under the Completed Tab it says I've completed 2 Classes ...
- Understanding and & Working With GIT
- Advanced Git

Below that, it says I've completed the first 5 P1XT GIT Lessons.

Thank you for taking the time to check this out!

**Comment by kimkwanka** [comment]
The thing is, that the P1XT Prerequisites course has 6 lessons though. So since you haven't completed that last one in there (I think it's "Git immersion") the whole course isn't completed yet. But by completing those lessons you DID in fact complete 2 other courses which share most of the lessons.

**Comment by jdmedlock** [comment]
The next MVP#1 release contains a number of improvements to the clarity and presentation of learning resources and progress. Let's revisit this after you've had a chance to review that release to see if it helps to resolve this.

**Comment by jdmedlock** [comment]
Waiting to close pending resolution of #84 so @AgedLace can validate

**Comment by AgedLace** [comment]
I don't want to do the wrong thing here.  I'm not sure what is meant by 'validated'.  If I understand correctly, I need to close this so the issue can be validated in the new iteration?
